### ISSUE TITLE
Error while loading rule 'spaced-comment'

### ISSUE THREAD

**Issue by larsthorup** [feross/eslint-config-standard#3]
I just upgraded from 3.3.0 to 3.4.0 and now get this error:

TypeError: Error while loading rule 'spaced-comment': Cannot read property 'length' of undefined
    at module.exports (C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\rules\spaced-comment.js:26:28)
    at C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\eslint.js:629:32
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\eslint.js:620:16)
    at processText (C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\cli-engine.js:200:27)
    at processFile (C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\cli-engine.js:225:12)
    at C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\cli-engine.js:317:26
    at walk (C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\util\traverse.js:81:9)
    at C:\r\larsthorup\amaze\node_modules\semistandard\node_modules\standard-engine\node_modules\eslint\lib\util\traverse.js:102:9
    at Array.forEach (native)

**Comment by feross** [comment]
Try updating your version of eslint to 0.24.0. I think that the `spaced-comment` rule was added in 0.24.0. Let me know if that fixes your issue.

**Comment by feross** [comment]
Oh, it looks like you're using semistandard. I just noticed that. You should probably open an issue on the [semistandard](https://github.com/Flet/semistandard). I think this is happening because semistandard depends on a version of eslint older than 0.24.

cc @Flet, who's the maintainer

**Comment by larsthorup** [comment]
Thanks, I've created: https://github.com/Flet/semistandard/issues/20
